version: "3"
services:
    database:
      image: mysql:latest
      container_name: mysqlcont
      hostname: mysql
      ports: 
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: "mysql"
        MYSQL_DATABASE: "contact_form_db"
        MYSQL_USER: "mysqluser"
        MYSQL_PASSWORD: "password"
      volumes:
        - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

        ### After running "docker-compose up -d", wait till 2 - 5 mins for the mysql setup.
        ### Alternatively, you can check in "docker container logs mysqlcont" 
        ### when you receive "[Entrypoint]: MySQL init process done. Ready for start up." in logs, it confirms setup is completed.

    databaseUI:
      image: phpmyadmin/phpmyadmin
      container_name: phpuicont
      hostname: phpui
      ports: 
        - "8080:80"
      environment:
        PMA_HOST: "mysqlcont"
        PMA_USER: "mysqluser"
        PMA_PASSWORD: "password"


    phphtml:
      image: ramesh0112/phpmysql:v1 
      container_name: frontend
      hostname: webserver
      ports: 
        - "9000:80"
      volumes:
        - ./html/:/var/www/html/
      depends_on:
        - database

